import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import MenuOverlay from "../components/MenuOverlay";
import Footer from "../components/Footer";
import Head from "next/head";
import Providers from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Grupo Noa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Head>
        <link rel="icon" href="/img/LOGO_WALTER-gradient.png" />
      </Head>
      <Providers>
        <body className={inter.className}>
          <MenuOverlay />
          <Navbar />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
